// Mocks generated by Mockito 5.4.6 from annotations
// in movie_recommendation_app/test/unit/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:movie_recommendation_app/core/utils/result.dart' as _i2;
import 'package:movie_recommendation_app/domain/services/authentication_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthenticationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationService extends _i1.Mock
    implements _i3.AuthenticationService {
  MockAuthenticationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Result<String>> createRequestToken() =>
      (super.noSuchMethod(
            Invocation.method(#createRequestToken, []),
            returnValue: _i4.Future<_i2.Result<String>>.value(
              _FakeResult_0<String>(
                this,
                Invocation.method(#createRequestToken, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<String>>);

  @override
  _i4.Future<_i2.Result<String>> createSession(String? approvedToken) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [approvedToken]),
            returnValue: _i4.Future<_i2.Result<String>>.value(
              _FakeResult_0<String>(
                this,
                Invocation.method(#createSession, [approvedToken]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<String>>);

  @override
  _i4.Future<_i2.Result<bool>> validateSession() =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, []),
            returnValue: _i4.Future<_i2.Result<bool>>.value(
              _FakeResult_0<bool>(
                this,
                Invocation.method(#validateSession, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<Map<String, dynamic>>> getAccountDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountDetails, []),
            returnValue: _i4.Future<_i2.Result<Map<String, dynamic>>>.value(
              _FakeResult_0<Map<String, dynamic>>(
                this,
                Invocation.method(#getAccountDetails, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  String getAuthenticationUrl(String? requestToken) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthenticationUrl, [requestToken]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getAuthenticationUrl, [requestToken]),
            ),
          )
          as String);

  @override
  _i4.Future<String?> getStoredUsername() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredUsername, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> getStoredAccountName() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredAccountName, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
