// Mocks generated by Mockito 5.4.6 from annotations
// in movie_recommendation_app/test/unit/providers/user_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_recommendation_app/core/utils/result.dart' as _i2;
import 'package:movie_recommendation_app/data/models/user_preferences.dart'
    as _i5;
import 'package:movie_recommendation_app/data/models/user_profile.dart' as _i6;
import 'package:movie_recommendation_app/domain/repositories/user_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<void>> saveUserPreferences(
    _i5.UserPreferences? preferences,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserPreferences, [preferences]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#saveUserPreferences, [preferences]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i5.UserPreferences?>> getUserPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getUserPreferences, []),
            returnValue: _i4.Future<_i2.Result<_i5.UserPreferences?>>.value(
              _FakeResult_0<_i5.UserPreferences?>(
                this,
                Invocation.method(#getUserPreferences, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.UserPreferences?>>);

  @override
  _i4.Future<_i2.Result<void>> saveUserProfile(_i6.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserProfile, [profile]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#saveUserProfile, [profile]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i6.UserProfile?>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i2.Result<_i6.UserProfile?>>.value(
              _FakeResult_0<_i6.UserProfile?>(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i6.UserProfile?>>);

  @override
  _i4.Future<_i2.Result<void>> saveImdbProfile(String? profileUrl) =>
      (super.noSuchMethod(
            Invocation.method(#saveImdbProfile, [profileUrl]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#saveImdbProfile, [profileUrl]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> saveLetterboxdProfile(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#saveLetterboxdProfile, [username]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#saveLetterboxdProfile, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<void>> saveGenrePreferences(List<String>? genres) =>
      (super.noSuchMethod(
            Invocation.method(#saveGenrePreferences, [genres]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#saveGenrePreferences, [genres]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<List<String>>> getGenrePreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getGenrePreferences, []),
            returnValue: _i4.Future<_i2.Result<List<String>>>.value(
              _FakeResult_0<List<String>>(
                this,
                Invocation.method(#getGenrePreferences, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<List<String>>>);

  @override
  _i4.Future<_i2.Result<void>> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#clearUserData, [])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);
}
